# Loaded for logins and interactive shells

. ~/.bin/dotFiles/bash/env
. ~/.bin/dotFiles/bash/config
. ~/.bin/dotFiles/bash/aliases
. ~/.bin/dotFiles/bash/function
. ~/.bin/dotFiles/bash/dev-tools
. ~/.bin/dotFiles/bash/fancy-git.sh
. ~/.bin/dotFiles/bash/motd
