              # Loaded for logins and scripts.

              # Run Scripts




      #sh ~/.screenlayout/arander.sh
           
      . ~/.bin/dotFiles/bash/env
     
      . ~/.bin/dotFiles/bash/config

      . ~/.bin/dotFiles/bash/aliases

      . ~/.bin/dotFiles/bash/prompt

      . ~/.bin/dotFiles/bash/function

      . ~/.bin/dotFiles/bash/fancy-git.sh